(() => {
 document.querySelectorAll('.fw-phone-presentation').forEach(phone=>{
  const screen=phone.querySelector('.fw-phone-screen'),back=phone.querySelector('[data-screen-back]'),next=phone.querySelector('[data-screen-next]'),horizontal=screen.classList.contains('is-horizontal');
  const update=()=>{const position=horizontal?screen.scrollLeft:screen.scrollTop,size=horizontal?screen.clientWidth:screen.clientHeight,total=horizontal?screen.scrollWidth:screen.scrollHeight;back.disabled=position<2;next.disabled=position+size>=total-2};
  const move=direction=>screen.scrollBy({left:horizontal?direction*screen.clientWidth:0,top:horizontal?0:direction*screen.clientHeight,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
  back.addEventListener('click',()=>move(-1));next.addEventListener('click',()=>move(1));screen.addEventListener('scroll',update,{passive:true});screen.addEventListener('load',update,true);new ResizeObserver(update).observe(screen);
  const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){const img=entry.target;img.src=img.dataset.phoneSrc;img.removeAttribute('data-phone-src');observer.unobserve(img)}},{root:screen,rootMargin:'600px'});
  screen.querySelectorAll('[data-phone-src]').forEach(img=>observer.observe(img));update();
 });
 const dialog=document.createElement('dialog');dialog.className='fw-reader';dialog.setAttribute('aria-labelledby','fw-reader-title');
 dialog.innerHTML='<div class="fw-reader-top"><h2 id="fw-reader-title"></h2><div class="fw-reader-actions"><button data-orientation hidden>切换横版</button><a data-original target="_blank" rel="noopener">原始长图 ↗</a><button data-qr hidden>项目二维码</button><button data-close>关闭 ×</button></div></div><p class="fw-reader-hint"></p><div class="fw-reader-scroll" tabindex="0" aria-label="完整漫画阅读区域"><div class="fw-reader-track"></div></div><aside class="fw-qr" hidden><img alt="项目原二维码"><p>二维码来自原作品集。</p><button data-hide-qr>收起二维码</button></aside>';
 document.body.append(dialog);const area=dialog.querySelector('.fw-reader-scroll'),track=dialog.querySelector('.fw-reader-track'),orientation=dialog.querySelector('[data-orientation]'),qr=dialog.querySelector('.fw-qr');let catalog,story,trigger,overflow='',horizontal=false,token=0;
 function render(){const tiles=horizontal&&story.horizontalTiles?story.horizontalTiles:story.tiles;area.classList.toggle('horizontal',horizontal);track.replaceChildren();for(const [i,t]of tiles.entries()){const image=new Image();image.src=t.src;image.width=t.width;image.height=t.height;image.alt=story.title+' · '+(i+1);image.loading=i<2?'eager':'lazy';image.decoding='async';track.append(image)}area.scrollTo(0,0);dialog.querySelector('.fw-reader-hint').textContent=horizontal?'横向阅读：左右滑动，或聚焦阅读区后使用方向键。':'竖向阅读：向下滚动查看完整故事。';orientation.textContent=horizontal?'切换竖版':'切换横版'}
 document.addEventListener('click',async e=>{const a=e.target.closest('[data-story]');if(!a||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey||!dialog.showModal)return;e.preventDefault();trigger=a;const current=++token;overflow=document.documentElement.style.overflow;document.documentElement.style.overflow='hidden';dialog.showModal();dialog.querySelector('[data-close]').focus();dialog.querySelector('h2').textContent='加载作品…';track.textContent='正在加载完整作品';qr.hidden=true;orientation.hidden=true;dialog.querySelector('[data-qr]').hidden=true;
  try{catalog??=fetch('/case-media/fantawild-stories/stories.json').then(r=>{if(!r.ok)throw Error();return r.json()});const all=await catalog;if(current!==token||!dialog.open)return;story=all.find(s=>s.slug===a.dataset.story);if(!story)throw Error();dialog.querySelector('h2').textContent=story.title;dialog.querySelector('[data-original]').href=story.full;horizontal=story.orientation==='horizontal';orientation.hidden=!story.horizontalTiles;dialog.querySelector('[data-qr]').hidden=!story.qr;if(story.qr)qr.querySelector('img').src=story.qr;render()}catch{catalog=null;track.textContent='暂时无法加载，请关闭后重试或打开原始长图。';dialog.querySelector('[data-original]').href=a.href}
 });
 orientation.addEventListener('click',()=>{horizontal=!horizontal;render()});dialog.querySelector('[data-close]').addEventListener('click',()=>dialog.close());dialog.querySelector('[data-qr]').addEventListener('click',()=>{qr.hidden=!qr.hidden});dialog.querySelector('[data-hide-qr]').addEventListener('click',()=>qr.hidden=true);dialog.addEventListener('close',()=>{token++;document.documentElement.style.overflow=overflow;track.replaceChildren();trigger?.focus({preventScroll:true})});
})();
