(() => {
 const root=document.querySelector('.archive-hero'); if(!root)return;
 const data=JSON.parse(document.getElementById('archive-data').textContent), stage=root.querySelector('.archive-stage'), ring=root.querySelector('.archive-ring'), reduce=matchMedia('(prefers-reduced-motion: reduce)');
 const descriptions=['从包装、展会到网站与 App，连接智能割草机器人的品牌与产品体验。','围绕带屏幕充电头，探索 UI、充电模式交互与产品外型。','从标志构思、视觉规范到品牌应用，建立统一的品牌识别。','用条漫、插画主视觉与数字页面，讲述主题乐园的故事。','山冭清：从视觉识别、包装到小程序与展会物料的品牌设计。','贯穿品牌识别与展会场景的视觉体验。','用角色造型和动态表情，把日常情绪变成可以分享的图像。','围绕白 T 计划展开的展览主视觉与系列视觉物料。','一本从数字 1 走向 100 的插画人像书，记录不同面孔与绘画探索。','以插画讲述搁浅的人，在画面中留下情绪与想象的空间。','从纸张原稿到文字展示，保留手写笔触的古拙质感。','围绕镜子展开的图像创作，探索观看与自我映照。','一组虚构城市的街景明信片，每一处风景都有自己的故事。','口罩时间里的旅居记录，以单幅画面与图文明信片呈现。','让诗的意向在图像、文字与动态影像之间流动。','从白底手写字到图像文字，再延伸到三维与动态表达。','以睡着的人为主题，描绘安静的姿态与片刻。','小人物、小物件与贴纸，在日常尺度里发现创作的趣味。','以复古海报语言描绘艺术家肖像，呈现绘画过程与人物表达。','用人物、造型与色彩，观察普通人的时尚表达。'];
 const cards=[...root.querySelectorAll('.archive-card')].map((el,i)=>{const b=document.createElement('button');b.type='button';b.className=el.className;b.dataset.index=i;b.setAttribute('aria-label','查看作品便签：'+data[i].title);b.innerHTML=el.innerHTML;const back=b.querySelector("img").cloneNode(true);back.className="archive-card-back";back.alt="";back.setAttribute("aria-hidden","true");b.append(back);for(const side of ["left","right"]){const edge=document.createElement("span");edge.className="archive-edge archive-edge-"+side;b.append(edge)}const surface=document.createElement("span");surface.className="archive-glass-surface";while(b.firstChild)surface.append(b.firstChild);b.append(surface);el.replaceWith(b);return b});
 const depthTitle=document.createElement('div');depthTitle.className='archive-depth-title';depthTitle.textContent='';for(const char of 'BANCI.STUDIO'){const letter=document.createElement('span');letter.className='archive-letter';letter.textContent=char;depthTitle.append(letter)}depthTitle.setAttribute('aria-hidden','true');stage.append(depthTitle);const positionTitle=()=>{const mobile=innerWidth<=700,size=innerWidth*.111;depthTitle.style.fontSize=size+'px';depthTitle.style.left=(stage.clientWidth-depthTitle.offsetWidth)/2+'px';depthTitle.style.top=(ring.offsetTop-size*.82*(mobile?2.8:2.45)/2)+'px';depthTitle.style.transform='translateZ(0)'}; const dialog=document.createElement('dialog');dialog.className='archive-note';dialog.setAttribute('aria-labelledby','archive-note-title');dialog.innerHTML='<button type="button" class="archive-note-close" aria-label="关闭作品便签">×</button><div class="archive-note-picture"><img alt=""></div><div class="archive-note-copy"><small></small><h2 id="archive-note-title"></h2><p></p><a>查看完整项目 ↗</a></div>';document.body.append(dialog);
 const toggle=document.createElement('button');toggle.type='button';toggle.dataset.archivePlay='';root.querySelector('.archive-controls').append(toggle);
 let order=[],index=0,yaw=0,raf=0,last=0,paused=reduce.matches,hover=false,visible=true,start=null,suppress=false,oldOverflow='';
 const modulo=n=>(n+data.length)%data.length;
 const update=()=>{index=modulo(Math.round(-yaw/(360/data.length))%data.length);const item=data[order[index]];root.querySelector('#archive-name').textContent=item.title;root.querySelector('#archive-category').textContent=item.category;root.querySelector('#archive-project').href=item.url;root.querySelector('#archive-count').textContent=String(index+1).padStart(2,'0')+' / '+data.length;cards.forEach((c,i)=>c.tabIndex=i===order[index]?0:-1)};

 let shadowFrame=0,shadowUntil=0;
 function renderShadows(time){shadowFrame=0;if(document.hidden||!visible)return;
 const faces=cards.map((c,i)=>{const a=(order.indexOf(i)*360/data.length+yaw)*Math.PI/180;return Math.cos(a)>.08?c.querySelector('.archive-glass-surface').getBoundingClientRect():null}).filter(Boolean);
 const glyphs=[...depthTitle.children].map(l=>({l,r:l.getBoundingClientRect(),h:l.offsetHeight}));
 for(const {l,r,h} of glyphs){if(!r.width||!r.height)continue;const sy=r.height/Math.max(1,h);const layers=faces.filter(c=>c.right+24>r.left&&c.left<r.right&&c.bottom+24>r.top&&c.top<r.bottom).map(c=>{const x=c.left+c.width*.5+12-r.left,y=(c.top+c.height*.5+18-r.top)/sy;return 'radial-gradient(ellipse '+(c.width*.64)+'px '+(c.height*.58/sy)+'px at '+x+'px '+y+'px,rgba(57,66,60,.33),rgba(57,66,60,.17) 52%,transparent 82%)'});l.style.backgroundImage=[...layers,'linear-gradient(#deded7,#deded7)'].join(',')}
 if(time<shadowUntil)shadowFrame=requestAnimationFrame(renderShadows);
 }
 function requestShadows(duration=0){shadowUntil=Math.max(shadowUntil,performance.now()+duration);if(!shadowFrame&&!document.hidden&&visible)shadowFrame=requestAnimationFrame(renderShadows)}
 cards.forEach(card=>{card.addEventListener('pointerenter',e=>{if(e.pointerType!=='mouse')return;card.classList.add('glass-active');requestShadows(650)});card.addEventListener('pointerleave',()=>{card.classList.remove('glass-active');requestShadows(650)});card.addEventListener('focus',()=>{card.classList.add('glass-active');requestShadows(650)});card.addEventListener('blur',()=>{card.classList.remove('glass-active');requestShadows(650)})});
 root.addEventListener('pointermove',()=>requestShadows(650));window.addEventListener('resize',()=>requestShadows(100));document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(shadowFrame);shadowFrame=0}else requestShadows()});
 const paint=()=>{ring.style.setProperty('--spin',yaw+'deg');update();requestShadows()};
 const layout=()=>{const mobile=innerWidth<=700;cards.forEach(card=>{const w=mobile?84:148,h=w*1400/739;Object.assign(card.style,{width:w+'px',height:h+'px',left:-w/2+'px',top:-h/2+'px'})});stage.style.setProperty('--radius',(mobile?320:550)+'px');stage.style.setProperty('--ring-scale',String(innerWidth*1.15/(mobile?660:1140)))}; const shuffle=()=>{order=data.map((_,i)=>i);for(let i=order.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[order[i],order[j]]=[order[j],order[i]]}cards.forEach((c,i)=>c.style.setProperty('--angle',order.indexOf(i)*(360/data.length)+'deg'));yaw=0;paint()};
 const canRun=()=>!paused&&!hover&&visible&&!document.hidden&&!dialog.open&&!start&&!root.contains(document.activeElement);
 function tick(time){raf=0;if(!canRun()){last=0;return}if(last)yaw-=Math.min(time-last,50)*.004;last=time;paint();raf=requestAnimationFrame(tick)}
 function sync(){toggle.textContent=paused?'播放':'暂停';toggle.setAttribute('aria-label',paused?'播放圆环自动旋转':'暂停圆环自动旋转');toggle.setAttribute('aria-pressed',String(!paused));if(canRun()){if(!raf)raf=requestAnimationFrame(tick)}else{cancelAnimationFrame(raf);raf=0;last=0}}
 const move=step=>{yaw=-((Math.round(-yaw/(360/data.length)))+step)*(360/data.length);paint()};
 function openNote(i){const d=data[i];dialog.querySelector('img').src=d.src;dialog.querySelector('img').alt=d.title;dialog.querySelector('small').textContent=d.category;dialog.querySelector('h2').textContent=d.title;dialog.querySelector('p').textContent=d.description;dialog.querySelector('a').href=d.url;oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog.showModal();sync()}
 cards.forEach((c,i)=>c.addEventListener('click',()=>{if(!suppress)openNote(i)}));
 root.querySelector('#archive-project').addEventListener('click',e=>{e.preventDefault();openNote(order[index])});
 dialog.querySelector('button').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>{document.body.style.overflow=oldOverflow;sync()});
 root.querySelector('[data-archive-prev]').onclick=()=>move(-1);root.querySelector('[data-archive-next]').onclick=()=>move(1);root.querySelector('[data-archive-shuffle]').onclick=shuffle;toggle.onclick=()=>{paused=!paused;toggle.blur();sync()};
 stage.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();move(e.key==='ArrowLeft'?-1:1)}});
 stage.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse'){hover=true;sync()}});stage.addEventListener('pointerleave',()=>{hover=false;sync()});
 stage.addEventListener('pointerdown',e=>{if(e.isPrimary&&e.button===0){start={x:e.clientX,y:e.clientY,id:e.pointerId};suppress=false;sync()}});
 window.addEventListener('pointerup',e=>{if(!start||start.id!==e.pointerId)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;start=null;suppress=Math.abs(dx)>12||Math.abs(dy)>12;if(Math.abs(dx)>35&&Math.abs(dx)>Math.abs(dy)*1.3)move(dx<0?1:-1);setTimeout(()=>suppress=false,0);sync()});window.addEventListener('pointercancel',()=>{start=null;sync()});
 root.addEventListener('focusin',sync);root.addEventListener('focusout',()=>setTimeout(sync,0));document.addEventListener('visibilitychange',sync);reduce.addEventListener('change',()=>{paused=reduce.matches;sync()});window.addEventListener('resize',layout);
 new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;sync()},{threshold:0}).observe(root);
 root.querySelector('#archive-count').removeAttribute('aria-live');root.querySelector('.archive-description p').textContent='点击查看项目 · 滑动切换';
 const letters=[...depthTitle.children];
 let waveTimers=[];
 function setLetterWave(center,strength=1){if(reduce.matches)return;waveTimers.forEach(clearTimeout);waveTimers=[];const base=innerWidth<=700?2.8:2.45;letters.forEach((letter,i)=>{const distance=Math.abs(i/(letters.length-1)-center),height=Math.exp(-Math.pow(distance/.22,2));const delay=Math.round(distance*160);waveTimers.push(setTimeout(()=>{letter.style.setProperty('--letter-scale',String(base+height*.85*strength));},delay))})}
 function resetLetterWave(){waveTimers.forEach(clearTimeout);letters.forEach((letter,i)=>{waveTimers.push(setTimeout(()=>letter.style.removeProperty('--letter-scale'),i*(360/data.length)))})}
 root.addEventListener('pointermove',e=>{if(e.pointerType!=='mouse')return;const r=depthTitle.getBoundingClientRect();setLetterWave(Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),1)});
 root.addEventListener('pointerleave',resetLetterWave);
 reduce.addEventListener('change',()=>{waveTimers.forEach(clearTimeout);letters.forEach(l=>l.style.removeProperty('--letter-scale'))}); const clamp=(v,n)=>Math.max(-n,Math.min(n,v));
 const tilt=(x,z)=>{if(reduce.matches)return;if(x===0&&z===0)resetLetterWave();else setLetterWave(.5+clamp(z,8)/16,Math.min(1,Math.abs(x)/6+.25));ring.style.setProperty('--tilt-x',clamp(x,10)+'deg');ring.style.setProperty('--tilt-z',clamp(z,8)+'deg')};
 stage.addEventListener('pointermove',e=>{if(e.pointerType!=='mouse')return;const r=stage.getBoundingClientRect();tilt((.5-(e.clientY-r.top)/r.height)*14,((e.clientX-r.left)/r.width-.5)*12)});
 root.addEventListener('pointerleave',()=>tilt(0,0));
 const motion=document.createElement('button');motion.type='button';motion.dataset.archiveMotion='';motion.textContent='开启体感';motion.setAttribute('aria-pressed','false');root.querySelector('.archive-controls').append(motion);
 const motionStatus=document.createElement('span');motionStatus.className='archive-motion-status';motionStatus.setAttribute('role','status');root.querySelector('.archive-controls').append(motionStatus);
 let motionActive=false,baseline=null,sensorTimer=0;
 const orient=e=>{if(!motionActive||!visible||document.hidden||dialog.open||e.beta===null||e.gamma===null)return;clearTimeout(sensorTimer);if(!baseline)baseline={b:e.beta,g:e.gamma};tilt((e.beta-baseline.b)*.35,(e.gamma-baseline.g)*.35)};
 const stopMotion=()=>{motionActive=false;baseline=null;clearTimeout(sensorTimer);window.removeEventListener('deviceorientation',orient);motion.textContent='开启体感';motion.setAttribute('aria-pressed','false');tilt(0,0)};
 motion.onclick=async()=>{if(motionActive){stopMotion();return}motionStatus.textContent='';if(reduce.matches){motionStatus.textContent='请先关闭系统的减少动态效果，再开启体感。';return}if(!window.isSecureContext||!window.DeviceOrientationEvent){motionStatus.textContent='体感需要支持的手机与 HTTPS 访问；仍可左右滑动。';return}try{if(typeof DeviceOrientationEvent.requestPermission==='function'&&await DeviceOrientationEvent.requestPermission()!=='granted'){motionStatus.textContent='未获体感授权，仍可左右滑动。';return}motionActive=true;baseline=null;window.addEventListener('deviceorientation',orient);motion.textContent='关闭体感';motion.setAttribute('aria-pressed','true');sensorTimer=setTimeout(()=>{stopMotion();motionStatus.textContent='未检测到方向传感器，仍可左右滑动。'},5000)}catch{stopMotion();motionStatus.textContent='体感暂不可用，仍可左右滑动。'}};
 window.addEventListener('orientationchange',()=>{baseline=null});document.addEventListener('visibilitychange',()=>{baseline=null});reduce.addEventListener('change',()=>{if(reduce.matches){stopMotion();ring.style.setProperty('--tilt-x','0deg');ring.style.setProperty('--tilt-z','0deg')}}); shuffle();layout();positionTitle();window.addEventListener("resize",positionTitle);root.classList.add('archive-ready');root.querySelector('.archive-controls').hidden=false;sync();
})();

