(() => {
 const root=document.querySelector('.archive-hero'); if(!root)return;
 const data=JSON.parse(document.getElementById('archive-data').textContent), stage=root.querySelector('.archive-stage'), ring=root.querySelector('.archive-ring'), reduce=matchMedia('(prefers-reduced-motion: reduce)');
 const descriptions=['从包装、展会到网站与 App，连接智能割草机器人的品牌与产品体验。','围绕带屏幕充电头，探索 UI、充电模式交互与产品外型。','从标志构思、视觉规范到品牌应用，建立统一的品牌识别。','用条漫、插画主视觉与数字页面，讲述主题乐园的故事。','山冭清：从视觉识别、包装到小程序与展会物料的品牌设计。','贯穿品牌识别与展会场景的视觉体验。','用角色造型和动态表情，把日常情绪变成可以分享的图像。','围绕白 T 计划展开的展览主视觉与系列视觉物料。','一本从数字 1 走向 100 的插画人像书，记录不同面孔与绘画探索。','以插画讲述搁浅的人，在画面中留下情绪与想象的空间。','从纸张原稿到文字展示，保留手写笔触的古拙质感。','围绕镜子展开的图像创作，探索观看与自我映照。','一组虚构城市的街景明信片，每一处风景都有自己的故事。','口罩时间里的旅居记录，以单幅画面与图文明信片呈现。','让诗的意向在图像、文字与动态影像之间流动。','从白底手写字到图像文字，再延伸到三维与动态表达。','以睡着的人为主题，描绘安静的姿态与片刻。','小人物、小物件与贴纸，在日常尺度里发现创作的趣味。','以复古海报语言描绘艺术家肖像，呈现绘画过程与人物表达。','用人物、造型与色彩，观察普通人的时尚表达。'];
 const cards=[...root.querySelectorAll('.archive-card')].map((el,i)=>{const b=document.createElement('button');b.type='button';b.className=el.className;b.dataset.index=i;b.setAttribute('aria-label','查看作品便签：'+data[i].title);b.innerHTML=el.innerHTML;const back=document.createElement("span");back.className="archive-card-back";back.style.backgroundImage="url("+data[i].src.replace("-hd.webp","-blur.webp")+")";back.style.backgroundSize="cover";back.style.backgroundPosition="center";back.setAttribute("aria-hidden","true");b.append(back);for(const side of ["left","right"]){const edge=document.createElement("span");edge.className="archive-edge archive-edge-"+side;b.append(edge)}const surface=document.createElement("span");surface.className="archive-surface";while(b.firstChild)surface.append(b.firstChild);b.append(surface);el.replaceWith(b);return b});
 const depthTitle=document.createElement('div');depthTitle.className='archive-depth-title';depthTitle.textContent='';for(const char of 'BANCI.STUDIO'){const letter=document.createElement('span');letter.className='archive-letter';letter.textContent=char;depthTitle.append(letter)}depthTitle.setAttribute('aria-hidden','true');stage.append(depthTitle);const positionTitle=()=>{const h=root.querySelector('h1'),r=h.getBoundingClientRect(),s=stage.getBoundingClientRect(),c=getComputedStyle(h);Object.assign(depthTitle.style,{left:(r.left-s.left)+'px',top:(r.top-s.top)+'px',fontSize:c.fontSize,transform:'translateZ(0) scaleY('+(innerWidth<=700?1.65:1.25)+')'})}; const dialog=document.createElement('dialog');dialog.className='archive-note';dialog.setAttribute('aria-labelledby','archive-note-title');dialog.innerHTML='<button type="button" class="archive-note-close" aria-label="关闭作品便签">×</button><div class="archive-note-picture"><img alt=""></div><div class="archive-note-copy"><small></small><h2 id="archive-note-title"></h2><p></p><a>查看完整项目 ↗</a></div>';document.body.append(dialog);
 const toggle=document.createElement('button');toggle.type='button';toggle.dataset.archivePlay='';root.querySelector('.archive-controls').append(toggle);
 let order=[],index=0,yaw=0,raf=0,last=0,paused=reduce.matches,hover=false,visible=true,start=null,suppress=false,oldOverflow='';
 const modulo=n=>(n+data.length)%data.length;
 const update=()=>{index=modulo(Math.round(-yaw/(360/data.length))%data.length);const item=data[order[index]];root.querySelector('#archive-name').textContent=item.title;root.querySelector('#archive-category').textContent=item.category;root.querySelector('#archive-project').href=item.url;root.querySelector('#archive-count').textContent=String(index+1).padStart(2,'0')+' / '+data.length;cards.forEach((c,i)=>c.tabIndex=i===order[index]?0:-1)};
 let springRaf=0,springTarget=0,springVelocity=0,springTime=0,paintingTime=0;const scales=cards.map(()=>({value:.78,velocity:0}));
 let shadowFrame=0;
 function updateTypeShadow(){shadowFrame=0;const front=cards.filter(c=>Number(c.style.getPropertyValue('--shadow-opacity'))>.095).map(c=>c.getBoundingClientRect());root.querySelectorAll('.archive-letter').forEach(letter=>{const r=letter.getBoundingClientRect();if(!r.width||!r.height)return;const shadows=front.filter(c=>c.right+28>r.left&&c.left-8<r.right&&c.bottom+30>r.top&&c.top<r.bottom).map(c=>{const x=((c.left+c.width/2+16-r.left)/r.width)*100,y=((c.top+c.height/2+24-r.top)/r.height)*100;return 'radial-gradient(ellipse '+Math.round(c.width*.65)+'px '+Math.round(c.height*.58)+'px at '+x+'% '+y+'%,rgba(81,83,73,.30) 0%,rgba(81,83,73,.16) 56%,transparent 80%)'});letter.style.backgroundImage=shadows.length?shadows.join(',')+',linear-gradient(#deded7,#deded7)':'linear-gradient(#deded7,#deded7)'})}
 const scheduleTypeShadow=()=>{if(!shadowFrame)shadowFrame=requestAnimationFrame(updateTypeShadow)};
 root.addEventListener('pointermove',scheduleTypeShadow);window.addEventListener('resize',scheduleTypeShadow);
 const paint=()=>{ring.style.setProperty('--spin',yaw+'deg');cards.forEach((card,i)=>{const angle=order.indexOf(i)*360/data.length+yaw,distance=Math.abs(((angle%360)+540)%360-180);card.style.setProperty('--spread','0deg');const far=(1-Math.cos(distance*Math.PI/180))/2;card.style.setProperty('--focus-scale',String(1-far*.36));card.style.setProperty('--shadow-opacity',String(.18*(1-far)));card.style.setProperty('--depth-offset',String(far*110)+'px');card.classList.toggle('is-current',distance<180/data.length);card.setAttribute('aria-current',distance<180/data.length?'true':'false')});update();scheduleTypeShadow()};
 const layout=()=>{const mobile=innerWidth<=700;cards.forEach(card=>{const w=mobile?120:190,h=w*1400/739;Object.assign(card.style,{width:w+'px',height:h+'px',left:-w/2+'px',top:-h/2+'px'})});stage.style.setProperty('--radius',(mobile?355:665)+'px');stage.style.setProperty('--ring-scale',String(mobile?innerWidth*1.2/700:innerWidth*1.2/1330))}; const shuffle=()=>{order=data.map((_,i)=>i);for(let i=order.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[order[i],order[j]]=[order[j],order[i]]}cards.forEach((c,i)=>c.style.setProperty('--angle',order.indexOf(i)*(360/data.length)+'deg'));cancelAnimationFrame(springRaf);springRaf=0;springVelocity=0;dwell=0;stepping=false;yaw=0;paint();sync()};
 let entering=false;const canRun=()=>!springRaf&&!entering&&!paused&&!hover&&visible&&!document.hidden&&!dialog.open&&!start&&!root.contains(document.activeElement);
 let dwell=0,stepElapsed=0,stepping=false,stepFrom=0,stepTo=0;
 const mechanicalEase=t=>t*t*(3-2*t);
 function tick(time){raf=0;if(!canRun()){last=0;return}const dt=last?Math.min(time-last,50):0;last=time;if(!stepping){dwell+=dt;if(dwell>=1700){stepping=true;stepElapsed=0;stepFrom=yaw;stepTo=yaw-360/data.length;dwell=0}}else{stepElapsed+=dt;const t=Math.min(1,stepElapsed/620);yaw=stepFrom+(stepTo-stepFrom)*mechanicalEase(t);paint();if(t===1){stepping=false;yaw=stepTo;paint()}}raf=requestAnimationFrame(tick)}
 function sync(){toggle.textContent=paused?'播放':'暂停';toggle.setAttribute('aria-label',paused?'播放圆环自动旋转':'暂停圆环自动旋转');toggle.setAttribute('aria-pressed',String(!paused));if(canRun()){if(!raf)raf=requestAnimationFrame(tick)}else{cancelAnimationFrame(raf);raf=0;last=0}}
 const move=step=>{const base=springRaf?springTarget:yaw;springTarget=-(Math.round(-base/(360/data.length))+step)*(360/data.length);cancelAnimationFrame(springRaf);cancelAnimationFrame(raf);raf=0;last=0;dwell=0;stepping=false;const from=yaw;let started=0;if(reduce.matches){yaw=springTarget;springRaf=0;paint();sync();return}function advance(time){if(!started)started=time;const t=Math.min(1,(time-started)/620);yaw=from+(springTarget-from)*mechanicalEase(t);paint();if(t<1)springRaf=requestAnimationFrame(advance);else{springRaf=0;sync()}}springRaf=requestAnimationFrame(advance)};

 function openNote(i){const d=data[i];dialog.querySelector('img').src=d.src;dialog.querySelector('img').alt=d.title;dialog.querySelector('small').textContent=d.category;dialog.querySelector('h2').textContent=d.title;dialog.querySelector('p').textContent=d.description;dialog.querySelector('a').href=d.url;oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog.showModal();sync()}
 cards.forEach((c,i)=>c.addEventListener('click',()=>{if(!suppress)openNote(i)}));
 root.querySelector('#archive-project').addEventListener('click',e=>{e.preventDefault();openNote(order[index])});
 dialog.querySelector('button').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>{document.body.style.overflow=oldOverflow;sync()});
 root.querySelector('[data-archive-prev]').onclick=()=>move(-1);root.querySelector('[data-archive-next]').onclick=()=>move(1);root.querySelector('[data-archive-shuffle]').onclick=shuffle;toggle.onclick=()=>{paused=!paused;toggle.blur();sync()};
 stage.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();move(e.key==='ArrowLeft'?-1:1)}});
 stage.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse'){hover=true;sync()}});stage.addEventListener('pointerleave',()=>{hover=false;sync()});
 stage.addEventListener('pointerdown',e=>{if(e.isPrimary&&e.button===0){start={x:e.clientX,y:e.clientY,id:e.pointerId};suppress=false;sync()}});
 window.addEventListener('pointerup',e=>{if(!start||start.id!==e.pointerId)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;start=null;suppress=Math.abs(dx)>12||Math.abs(dy)>12;if(Math.abs(dx)>35&&Math.abs(dx)>Math.abs(dy)*1.3)move(dx<0?1:-1);setTimeout(()=>suppress=false,0);sync()});window.addEventListener('pointercancel',()=>{start=null;sync()});
 root.addEventListener('focusin',sync);root.addEventListener('focusout',()=>setTimeout(sync,0));document.addEventListener('visibilitychange',sync);reduce.addEventListener('change',()=>{paused=reduce.matches;sync()});window.addEventListener('resize',layout);
 new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;sync()},{threshold:0}).observe(root);
 root.querySelector('#archive-count').removeAttribute('aria-live');root.querySelector('.archive-description p').textContent='点击作品查看便签 · 左右滑动浏览';
 const letters=[...depthTitle.children];
 let waveTimers=[];
 function setLetterWave(center,strength=1){if(reduce.matches)return;waveTimers.forEach(clearTimeout);waveTimers=[];const base=innerWidth<=700?2.8:2.45;letters.forEach((letter,i)=>{const distance=Math.abs(i/(letters.length-1)-center),height=Math.exp(-Math.pow(distance/.22,2));const delay=Math.round(distance*160);waveTimers.push(setTimeout(()=>{letter.style.setProperty('--letter-scale',String(base+height*.85*strength));},delay))})}
 function resetLetterWave(){waveTimers.forEach(clearTimeout);letters.forEach((letter,i)=>{waveTimers.push(setTimeout(()=>letter.style.removeProperty('--letter-scale'),i*(360/data.length)))})}
 root.addEventListener('pointermove',e=>{if(e.pointerType!=='mouse')return;const r=depthTitle.getBoundingClientRect();setLetterWave(Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),1)});
 root.addEventListener('pointerleave',resetLetterWave);
 reduce.addEventListener('change',()=>{waveTimers.forEach(clearTimeout);letters.forEach(l=>l.style.removeProperty('--letter-scale'))}); cards.forEach(card=>{card.addEventListener('pointerenter',e=>{if(e.pointerType!=='mouse')return;const slot=order.indexOf(Number(card.dataset.index)),angle=slot*360/data.length+yaw,signed=((angle%360)+540)%360-180;card.style.setProperty('--hover-y',Math.max(-16,Math.min(16,-signed*.22))+'deg');card.classList.add('is-hovered')});card.addEventListener('pointerleave',()=>card.classList.remove('is-hovered'));card.addEventListener('blur',()=>card.classList.remove('is-hovered'))}); const clamp=(v,n)=>Math.max(-n,Math.min(n,v));
 const tilt=(x,z)=>{if(reduce.matches)return;if(x===0&&z===0)resetLetterWave();else setLetterWave(.5+clamp(z,8)/16,Math.min(1,Math.abs(x)/6+.25));ring.style.setProperty('--tilt-x',clamp(x,10)+'deg');ring.style.setProperty('--tilt-z',clamp(z,8)+'deg')};
 stage.addEventListener('pointermove',e=>{if(e.pointerType!=='mouse')return;const r=stage.getBoundingClientRect();tilt((.5-(e.clientY-r.top)/r.height)*14,((e.clientX-r.left)/r.width-.5)*12)});
 root.addEventListener('pointerleave',()=>tilt(0,0));
 const motion=document.createElement('button');motion.type='button';motion.dataset.archiveMotion='';motion.textContent='开启体感';motion.setAttribute('aria-pressed','false');root.querySelector('.archive-controls').append(motion);
 const motionStatus=document.createElement('span');motionStatus.className='archive-motion-status';motionStatus.setAttribute('role','status');root.querySelector('.archive-controls').append(motionStatus);
 let motionActive=false,baseline=null,sensorTimer=0;
 const orient=e=>{if(!motionActive||!visible||document.hidden||dialog.open||e.beta===null||e.gamma===null)return;clearTimeout(sensorTimer);if(!baseline)baseline={b:e.beta,g:e.gamma};tilt((e.beta-baseline.b)*.35,(e.gamma-baseline.g)*.35)};
 const stopMotion=()=>{motionActive=false;baseline=null;clearTimeout(sensorTimer);window.removeEventListener('deviceorientation',orient);motion.textContent='开启体感';motion.setAttribute('aria-pressed','false');tilt(0,0)};
 motion.onclick=async()=>{if(motionActive){stopMotion();return}motionStatus.textContent='';if(reduce.matches){motionStatus.textContent='请先关闭系统的减少动态效果，再开启体感。';return}if(!window.isSecureContext||!window.DeviceOrientationEvent){motionStatus.textContent='体感需要支持的手机与 HTTPS 访问；仍可左右滑动。';return}try{if(typeof DeviceOrientationEvent.requestPermission==='function'&&await DeviceOrientationEvent.requestPermission()!=='granted'){motionStatus.textContent='未获体感授权，仍可左右滑动。';return}motionActive=true;baseline=null;window.addEventListener('deviceorientation',orient);motion.textContent='关闭体感';motion.setAttribute('aria-pressed','true');sensorTimer=setTimeout(()=>{stopMotion();motionStatus.textContent='未检测到方向传感器，仍可左右滑动。'},5000)}catch{stopMotion();motionStatus.textContent='体感暂不可用，仍可左右滑动。'}};
 window.addEventListener('orientationchange',()=>{baseline=null});document.addEventListener('visibilitychange',()=>{baseline=null});reduce.addEventListener('change',()=>{if(reduce.matches){stopMotion();ring.style.setProperty('--tilt-x','0deg');ring.style.setProperty('--tilt-z','0deg')}}); shuffle();layout();positionTitle();window.addEventListener("resize",positionTitle);root.classList.add('archive-ready');root.querySelector('.archive-controls').hidden=false;


 sync();
})();
